version: "3.8"

services:
  spammy:
    build: ./
    ports:
      - '587:587'
      - '25:25'
    environment:
      - MAIL_LOGIN
      - MAIL_PASSWORD
    deploy:
      restart_policy:
        condition: on-failure
