version: "3.8"

services:
  spammy:
    build: ./
    ports:
      - '587:587'
      - '25:25'
    environment:
      - SENDER_MAIL_LOGIN
      - SENDER_MAIL_PASSWORD
      - RECEIVER_MAIL
    deploy:
      restart_policy:
        condition: on-failure
